POST http://localhost:8080/v1/cart
Content-Type: application/json

{}

###
GET http://localhost:8080/v1/cart/1
Accept: application/json

###
PUT http://localhost:8080/v1/cart
Content-Type: application/json

{}

###
POST http://localhost:8080/v1/cart/order
Content-Type: application/json

{}

###
DELETE http://localhost:8080/v1/cart/1
Accept: application/json

###